[package]
name = "gutendemo"
version = "0.1.0"
authors = ["Stephen Molyneaux <WimbledonLabs@github.com>"]

[dependencies]
rocket = "0.3.15"
rocket_codegen = "0.3.15"
rocket_contrib = "0.3.15"
serde_derive = "*"
